// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: bootcamp_service/response/bootcamps.proto

package response

import (
	types "github.com/dipanshuchaubey/protos-package/bootcamp_service/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBootcampsDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetBootcampsDetailsResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBootcampsDetailsResponse) Reset() {
	*x = GetBootcampsDetailsResponse{}
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootcampsDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootcampsDetailsResponse) ProtoMessage() {}

func (x *GetBootcampsDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootcampsDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetBootcampsDetailsResponse) Descriptor() ([]byte, []int) {
	return file_bootcamp_service_response_bootcamps_proto_rawDescGZIP(), []int{0}
}

func (x *GetBootcampsDetailsResponse) GetData() []*GetBootcampsDetailsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateBootcampResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data    *types.BootcampInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateBootcampResponse) Reset() {
	*x = CreateBootcampResponse{}
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBootcampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBootcampResponse) ProtoMessage() {}

func (x *CreateBootcampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBootcampResponse.ProtoReflect.Descriptor instead.
func (*CreateBootcampResponse) Descriptor() ([]byte, []int) {
	return file_bootcamp_service_response_bootcamps_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBootcampResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBootcampResponse) GetData() *types.BootcampInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBootcampsDetailsResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bootcamp *types.BootcampInfo `protobuf:"bytes,1,opt,name=bootcamp,proto3" json:"bootcamp,omitempty"`
	Course   *types.CourseInfo   `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	Reviews  []*types.Review     `protobuf:"bytes,3,rep,name=reviews,proto3" json:"reviews,omitempty"`
}

func (x *GetBootcampsDetailsResponse_Data) Reset() {
	*x = GetBootcampsDetailsResponse_Data{}
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootcampsDetailsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootcampsDetailsResponse_Data) ProtoMessage() {}

func (x *GetBootcampsDetailsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bootcamp_service_response_bootcamps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootcampsDetailsResponse_Data.ProtoReflect.Descriptor instead.
func (*GetBootcampsDetailsResponse_Data) Descriptor() ([]byte, []int) {
	return file_bootcamp_service_response_bootcamps_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetBootcampsDetailsResponse_Data) GetBootcamp() *types.BootcampInfo {
	if x != nil {
		return x.Bootcamp
	}
	return nil
}

func (x *GetBootcampsDetailsResponse_Data) GetCourse() *types.CourseInfo {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *GetBootcampsDetailsResponse_Data) GetReviews() []*types.Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_bootcamp_service_response_bootcamps_proto protoreflect.FileDescriptor

var file_bootcamp_service_response_bootcamps_proto_rawDesc = []byte{
	0x0a, 0x29, 0x62, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x62, 0x6f, 0x6f, 0x74,
	0x63, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x62, 0x6f, 0x6f,
	0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x26, 0x62, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62,
	0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf,
	0x02, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x73, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x62,
	0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74,
	0x63, 0x61, 0x6d, 0x70, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0xbe, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x74,
	0x63, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x6f, 0x6f,
	0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x62, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x12, 0x3a, 0x0a, 0x06, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x6f, 0x6f,
	0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x63, 0x61,
	0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73,
	0x22, 0x6c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x63, 0x61,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x74,
	0x63, 0x61, 0x6d, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x4e,
	0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x70,
	0x61, 0x6e, 0x73, 0x68, 0x75, 0x63, 0x68, 0x61, 0x75, 0x62, 0x65, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x62, 0x6f, 0x6f, 0x74,
	0x63, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bootcamp_service_response_bootcamps_proto_rawDescOnce sync.Once
	file_bootcamp_service_response_bootcamps_proto_rawDescData = file_bootcamp_service_response_bootcamps_proto_rawDesc
)

func file_bootcamp_service_response_bootcamps_proto_rawDescGZIP() []byte {
	file_bootcamp_service_response_bootcamps_proto_rawDescOnce.Do(func() {
		file_bootcamp_service_response_bootcamps_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootcamp_service_response_bootcamps_proto_rawDescData)
	})
	return file_bootcamp_service_response_bootcamps_proto_rawDescData
}

var file_bootcamp_service_response_bootcamps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bootcamp_service_response_bootcamps_proto_goTypes = []any{
	(*GetBootcampsDetailsResponse)(nil),      // 0: bootcamp_service.response.GetBootcampsDetailsResponse
	(*CreateBootcampResponse)(nil),           // 1: bootcamp_service.response.CreateBootcampResponse
	(*GetBootcampsDetailsResponse_Data)(nil), // 2: bootcamp_service.response.GetBootcampsDetailsResponse.Data
	(*types.BootcampInfo)(nil),               // 3: bootcamp_service.types.BootcampInfo
	(*types.CourseInfo)(nil),                 // 4: bootcamp_service.types.CourseInfo
	(*types.Review)(nil),                     // 5: bootcamp_service.types.Review
}
var file_bootcamp_service_response_bootcamps_proto_depIdxs = []int32{
	2, // 0: bootcamp_service.response.GetBootcampsDetailsResponse.data:type_name -> bootcamp_service.response.GetBootcampsDetailsResponse.Data
	3, // 1: bootcamp_service.response.CreateBootcampResponse.data:type_name -> bootcamp_service.types.BootcampInfo
	3, // 2: bootcamp_service.response.GetBootcampsDetailsResponse.Data.bootcamp:type_name -> bootcamp_service.types.BootcampInfo
	4, // 3: bootcamp_service.response.GetBootcampsDetailsResponse.Data.course:type_name -> bootcamp_service.types.CourseInfo
	5, // 4: bootcamp_service.response.GetBootcampsDetailsResponse.Data.reviews:type_name -> bootcamp_service.types.Review
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bootcamp_service_response_bootcamps_proto_init() }
func file_bootcamp_service_response_bootcamps_proto_init() {
	if File_bootcamp_service_response_bootcamps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootcamp_service_response_bootcamps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bootcamp_service_response_bootcamps_proto_goTypes,
		DependencyIndexes: file_bootcamp_service_response_bootcamps_proto_depIdxs,
		MessageInfos:      file_bootcamp_service_response_bootcamps_proto_msgTypes,
	}.Build()
	File_bootcamp_service_response_bootcamps_proto = out.File
	file_bootcamp_service_response_bootcamps_proto_rawDesc = nil
	file_bootcamp_service_response_bootcamps_proto_goTypes = nil
	file_bootcamp_service_response_bootcamps_proto_depIdxs = nil
}
