# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bootcamp_service/response/bootcamps.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bootcamp_service/response/bootcamps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bootcamp_service.types import bootcamps_pb2 as bootcamp__service_dot_types_dot_bootcamps__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)bootcamp_service/response/bootcamps.proto\x12\x19\x62ootcamp_service.response\x1a&bootcamp_service/types/bootcamps.proto\"\x8e\x02\n\x1bGetBootcampsDetailsResponse\x12I\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32;.bootcamp_service.response.GetBootcampsDetailsResponse.Data\x1a\xa3\x01\n\x04\x44\x61ta\x12\x36\n\x08\x62ootcamp\x18\x01 \x01(\x0b\x32$.bootcamp_service.types.BootcampInfo\x12\x32\n\x06\x63ourse\x18\x02 \x01(\x0b\x32\".bootcamp_service.types.CourseInfo\x12/\n\x07reviews\x18\x03 \x03(\x0b\x32\x1e.bootcamp_service.types.Review\"]\n\x16\x43reateBootcampResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x32\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32$.bootcamp_service.types.BootcampInfoBNZLgithub.com/dipanshuchaubey/protos-package/bootcamp_service/response;responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bootcamp_service.response.bootcamps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/dipanshuchaubey/protos-package/bootcamp_service/response;response'
  _globals['_GETBOOTCAMPSDETAILSRESPONSE']._serialized_start=113
  _globals['_GETBOOTCAMPSDETAILSRESPONSE']._serialized_end=383
  _globals['_GETBOOTCAMPSDETAILSRESPONSE_DATA']._serialized_start=220
  _globals['_GETBOOTCAMPSDETAILSRESPONSE_DATA']._serialized_end=383
  _globals['_CREATEBOOTCAMPRESPONSE']._serialized_start=385
  _globals['_CREATEBOOTCAMPRESPONSE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
