# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bootcamp_service/types/bootcamps.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bootcamp_service/types/bootcamps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&bootcamp_service/types/bootcamps.proto\x12\x16\x62ootcamp_service.types\"\x8b\x01\n\x0c\x42ootcampInfo\x12\x13\n\x0b\x62ootcamp_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07website\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x11\n\tname_slug\x18\x06 \x01(\t\x12\x0f\n\x07\x63\x61reers\x18\x07 \x03(\t\"C\n\nCourseInfo\x12\x11\n\tcourse_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\\\n\x06Review\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x05\x42HZFgithub.com/dipanshuchaubey/protos-package/bootcamp_service/types;typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bootcamp_service.types.bootcamps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/dipanshuchaubey/protos-package/bootcamp_service/types;types'
  _globals['_BOOTCAMPINFO']._serialized_start=67
  _globals['_BOOTCAMPINFO']._serialized_end=206
  _globals['_COURSEINFO']._serialized_start=208
  _globals['_COURSEINFO']._serialized_end=275
  _globals['_REVIEW']._serialized_start=277
  _globals['_REVIEW']._serialized_end=369
# @@protoc_insertion_point(module_scope)
