# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_service/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17user_service/user.proto\x12\x0fuser_service.v1\x1a google/protobuf/descriptor.proto\"4\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\"6\n\x0fGetUsersRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\"\x7f\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12-\n\tuser_type\x18\x05 \x01(\x0e\x32\x1a.user_service.v1.UserTypes\"K\n\x0fGetUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x19.user_service.v1.UserInfo\"L\n\x10GetUsersResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x19.user_service.v1.UserInfo*~\n\tUserTypes\x12+\n\x15USER_TYPE_UNSPECIFIED\x10\x00\x1a\x10\xc2>\rNot Specified\x12\x1f\n\x10USER_TYPE_ACTIVE\x10\x01\x1a\t\xc2>\x06\x41\x63tive\x12#\n\x12USER_TYPE_INACTIVE\x10\x02\x1a\x0b\xc2>\x08Inactive2\xb0\x01\n\x0bUserService\x12N\n\x07GetUser\x12\x1f.user_service.v1.GetUserRequest\x1a .user_service.v1.GetUserResponse\"\x00\x12Q\n\x08GetUsers\x12 .user_service.v1.GetUsersRequest\x1a!.user_service.v1.GetUsersResponse\"\x00:1\n\x05label\x12!.google.protobuf.EnumValueOptions\x18\xe8\x07 \x01(\tB;Z9github.com/dipanshuchaubey/protos-package/user_service/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/dipanshuchaubey/protos-package/user_service/v1'
  _globals['_USERTYPES'].values_by_name["USER_TYPE_UNSPECIFIED"]._loaded_options = None
  _globals['_USERTYPES'].values_by_name["USER_TYPE_UNSPECIFIED"]._serialized_options = b'\302>\rNot Specified'
  _globals['_USERTYPES'].values_by_name["USER_TYPE_ACTIVE"]._loaded_options = None
  _globals['_USERTYPES'].values_by_name["USER_TYPE_ACTIVE"]._serialized_options = b'\302>\006Active'
  _globals['_USERTYPES'].values_by_name["USER_TYPE_INACTIVE"]._loaded_options = None
  _globals['_USERTYPES'].values_by_name["USER_TYPE_INACTIVE"]._serialized_options = b'\302>\010Inactive'
  _globals['_USERTYPES']._serialized_start=472
  _globals['_USERTYPES']._serialized_end=598
  _globals['_GETUSERREQUEST']._serialized_start=78
  _globals['_GETUSERREQUEST']._serialized_end=130
  _globals['_GETUSERSREQUEST']._serialized_start=132
  _globals['_GETUSERSREQUEST']._serialized_end=186
  _globals['_USERINFO']._serialized_start=188
  _globals['_USERINFO']._serialized_end=315
  _globals['_GETUSERRESPONSE']._serialized_start=317
  _globals['_GETUSERRESPONSE']._serialized_end=392
  _globals['_GETUSERSRESPONSE']._serialized_start=394
  _globals['_GETUSERSRESPONSE']._serialized_end=470
  _globals['_USERSERVICE']._serialized_start=601
  _globals['_USERSERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
