# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bootcamp_service/request/bootcamps.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bootcamp_service/request/bootcamps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(bootcamp_service/request/bootcamps.proto\x12\x18\x62ootcamp_service.request\"2\n\x1aGetBootcampsDetailsRequest\x12\x14\n\x0c\x62ootcamp_ids\x18\x01 \x03(\t\"\x8c\x01\n\x15\x43reateBootcampRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07website\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0f\n\x07\x63\x61reers\x18\x06 \x03(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\tBLZJgithub.com/dipanshuchaubey/protos-package/bootcamp_service/request;requestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bootcamp_service.request.bootcamps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/dipanshuchaubey/protos-package/bootcamp_service/request;request'
  _globals['_GETBOOTCAMPSDETAILSREQUEST']._serialized_start=70
  _globals['_GETBOOTCAMPSDETAILSREQUEST']._serialized_end=120
  _globals['_CREATEBOOTCAMPREQUEST']._serialized_start=123
  _globals['_CREATEBOOTCAMPREQUEST']._serialized_end=263
# @@protoc_insertion_point(module_scope)
